[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.cursor]
cursor = "0xffffff"
text = "0xF81CE5"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xd0d0d0"
yellow = "0xfeff00"

[colors.primary]
foreground = "0xffffff"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "DroidSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "DroidSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "DroidSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "DroidSansM Nerd Font Mono"
style = "Regular"

[scrolling]
history = 5000

[shell]
program = "/usr/bin/tmux"

[window]
decorations = "none"
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
